/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import com.mysql.cj.protocol.Resultset;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;



public class Activité extends javax.swing.JFrame {

    /**
     * Creates new form TBL2
     */
    public Activité() {
        initComponents();
        ShowI();
    }
Connection Con = null;
    Statement St = null, St1 = null;
    Resultset Rs = null, Rs1 = null;
    
  public void Connect_DB(){
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gst_act","root", "");
            } catch (SQLException Ex){
            JOptionPane.showMessageDialog(null, "Impossible de se connecter à la BASE DE DONNÉES.");
            }   
  }
     private void ShowI(){
        try {
            Connect_DB();
            St = Con.createStatement();
            Rs =  (Resultset) St.executeQuery("SELECT * FROM `activité`");
            jTable1.setModel(DbUtils.resultSetToTableModel((ResultSet) Rs));
            Con.close();
        }catch (Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomact = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        tarif = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jadd = new javax.swing.JButton();
        jedit = new javax.swing.JButton();
        jdelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nomis = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Activité");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/act.png"))); // NOI18N
        jLabel1.setText("Les activités");
        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 210, 70));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nom de l'activité:");
        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 140, 30));

        nomact.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        nomact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomactActionPerformed(evt);
            }
        });
        jPanel1.add(nomact, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 140, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Type d'installation:");
        jLabel4.setBackground(new java.awt.Color(0, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 160, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Tarif d'instalation:");
        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 140, 30));

        type.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 140, 30));

        tarif.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifActionPerformed(evt);
            }
        });
        jPanel1.add(tarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 140, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 530, 320));

        jadd.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        jadd.setText("Ajouter");
        jadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddActionPerformed(evt);
            }
        });
        jPanel1.add(jadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 150, 30));

        jedit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/compose.png"))); // NOI18N
        jedit.setText("Modifier");
        jedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeditActionPerformed(evt);
            }
        });
        jPanel1.add(jedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 150, 30));

        jdelete.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jdelete.setText("Supprimer");
        jdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 150, 30));

        jLabel6.setText("DA.");
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));

        nomis.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        nomis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomisActionPerformed(evt);
            }
        });
        jPanel1.add(nomis, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 140, 30));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nom d'installation:");
        jLabel7.setBackground(new java.awt.Color(0, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        back.setText("Menu");
        back.setBackground(new java.awt.Color(0, 153, 153));
        back.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        back.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("La liste des activités");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 530, -1));

        Print.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/printer.png"))); // NOI18N
        Print.setText("Imprimer");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel1.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 510, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void jeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeditActionPerformed
        // TODO add your handling code here:
           int index = jTable1.getSelectedRow();
   if (index == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une activité à modifier.");
        }else {
            Connect_DB();
            try {
                PreparedStatement Pst = Con.prepareStatement("UPDATE `activité` SET Nom_act=? ,Nom_is=? ,Type_is=?, Tar_is=? WHERE Id_act=? ");
                Pst.setString(1,nomact.getText());
                Pst.setString(2, nomis.getText());
                Pst.setString(3, type.getText());
                Pst.setInt(4, Integer.parseInt(tarif.getText()));
                Pst.setString(5, Key);
                
                JOptionPane.showMessageDialog(null, "Activité modifiée avec succès !");
                int row = Pst.executeUpdate();
                Con.close();
                  ShowI();
                nomact.setText("");
                nomis.setText("");
                type.setText("");
                tarif.setText("");
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Erreur de base de données");
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "Format de nombre incorrect");
}


        }
    }//GEN-LAST:event_jeditActionPerformed

    private void nomactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomactActionPerformed

    private void jaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(nomact.getText().isEmpty() ||nomis.getText().isEmpty() || type.getText().isEmpty() || tarif.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Veuillez entrer vos informations!");
         else{
              Connect_DB();
                       try {
                PreparedStatement Pst = Con.prepareStatement("INSERT INTO activité (`Nom_act`, `Nom_is`, `Type_is`, `Tar_is`) VALUES (?,?,?,?)");
                Pst.setString(1, nomact.getText());
                Pst.setString(2, nomis.getText());
                Pst.setString(3, type.getText());
                Pst.setInt(4, Integer.parseInt(tarif.getText()));
                JOptionPane.showMessageDialog(null, "Activité ajoutée avec succès !");
               
                int row = Pst.executeUpdate();
                Con.close();
                ShowI();
                nomact.setText("");
                nomis.setText("");
                type.setText("");
                tarif.setText("");
       } catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Erreur de base de données");
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "Format de nombre incorrect");
}


 }
    }//GEN-LAST:event_jaddActionPerformed

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jdeleteActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
    if (index == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner une Activité à supprimer.");
        return;
    }

    int dialogResult = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr de vouloir supprimer cette Activité ?", "Attention", JOptionPane.YES_NO_OPTION);
    if (dialogResult == JOptionPane.YES_OPTION) {{
            Connect_DB();
            try {
                PreparedStatement Pst = Con.prepareStatement("DELETE FROM `activité` WHERE Id_act =?");
                Pst.setString(1,Key);
                int row = Pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Activité supprimée avec succès !");
                Con.close();
                ShowI();
                
                nomact.setText("");
                nomis.setText("");
                type.setText("");
                tarif.setText("");
                } catch (SQLException ex) {
       
           }}}
        
    }//GEN-LAST:event_jdeleteActionPerformed

    private void nomisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomisActionPerformed

    private void tarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifActionPerformed
        String Key = null;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int MyIndex = jTable1.getSelectedRow();
        Key = model.getValueAt(MyIndex, 0).toString();
        nomact.setText(model.getValueAt(MyIndex, 1).toString());
        nomis.setText(model.getValueAt(MyIndex, 2).toString());
        type.setText(model.getValueAt(MyIndex, 3).toString());
        tarif.setText(model.getValueAt(MyIndex, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
Menu2 menuu = new Menu2();
menuu.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        try {
            jTable1.print();
        } catch (PrinterException e) {
        }
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activité.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activité.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activité.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activité.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activité().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jadd;
    private javax.swing.JButton jdelete;
    private javax.swing.JButton jedit;
    private javax.swing.JTextField nomact;
    private javax.swing.JTextField nomis;
    private javax.swing.JTextField tarif;
    private javax.swing.JTextField type;
    // End of variables declaration//GEN-END:variables
}
