/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import com.mysql.cj.protocol.Resultset;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.awt.print.PrinterException;


public class Organisateur2 extends javax.swing.JFrame {

    /**
     * Creates new form Organisateur2
     */
    public Organisateur2() {
        initComponents();
        ShowI();
    }
        
        Connection Con = null;
    Statement St = null, St1 = null;
    Resultset Rs = null, Rs1 = null;

    public void Connect_DB(){
        try{
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/gst_act","root", "");
            } catch (SQLException Ex){
            JOptionPane.showMessageDialog(null, "Impossible de se connecter à la BASE DE DONNÉES.");
            }
    }
    
    private void ShowI(){
        try {
            Connect_DB();
            St = Con.createStatement();
            Rs =  (Resultset) St.executeQuery("SELECT * FROM `organisateur`");
            jTable1.setModel(DbUtils.resultSetToTableModel((ResultSet) Rs));
            Con.close();
        }catch (Exception e){
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        mail = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        nom_os = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Organisateur");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nom:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 50, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Prénom:");
        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 70, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Adresse:");
        jLabel4.setBackground(new java.awt.Color(0, 153, 153));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 70, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Telephone:");
        jLabel5.setBackground(new java.awt.Color(0, 153, 153));
        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 90, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("E-mail:");
        jLabel6.setBackground(new java.awt.Color(0, 153, 153));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 70, 30));

        phone.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 160, 30));

        prenom.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });
        jPanel1.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 160, 30));

        name.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 160, 30));

        mail.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailActionPerformed(evt);
            }
        });
        jPanel1.add(mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 210, 30));

        address.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, 30));

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        Delete.setText("Supprimer");
        Delete.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 140, 40));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nom D'organisation:");
        jLabel8.setBackground(new java.awt.Color(0, 153, 153));
        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 160, 30));

        nom_os.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        nom_os.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_osActionPerformed(evt);
            }
        });
        jPanel1.add(nom_os, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 210, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "Title 6"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 1060, 270));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/org.png"))); // NOI18N
        jLabel9.setText("Les Organisateurs");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 260, 70));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        add.setText("Ajouter");
        add.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 140, 40));

        Edit.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/compose.png"))); // NOI18N
        Edit.setText("Modifier");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        jPanel1.add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 140, 40));

        back.setBackground(new java.awt.Color(0, 153, 153));
        back.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        back.setText("Menu");
        back.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("La liste des organisateurs");
        jLabel12.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 1060, -1));

        Print.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/printer.png"))); // NOI18N
        Print.setText("Imprimer");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel1.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        int index = jTable1.getSelectedRow();
    if (index == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un organisateur à supprimer.");
        return;
    }

    int dialogResult = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr de vouloir supprimer cet organisateur ?", "Attention", JOptionPane.YES_NO_OPTION);
    if (dialogResult == JOptionPane.YES_OPTION) {{
            Connect_DB();
            try {
                PreparedStatement Pst = Con.prepareStatement("DELETE FROM `organisateur` WHERE id_os = ?");
                Pst.setString(1,Key);
                int row = Pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Organisateur supprimée avec succès !");
                Con.close();
                ShowI();              
                
                nom_os.setText("");
                name.setText("");
                prenom.setText("");
                address.setText("");
                phone.setText("");
                mail.setText("");
               

            } catch (SQLException ex) {
            }
        }}
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteActionPerformed

    private void nom_osActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_osActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_osActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed

               DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
 if(name.getText().isEmpty() || prenom.getText().isEmpty() || address.getText().isEmpty() || phone.getText().isEmpty() || mail.getText().isEmpty() || nom_os.getText().isEmpty())
                 JOptionPane.showMessageDialog(null, "Veuillez entrer vos informations!");
 else{
     Connect_DB();
            try {
                PreparedStatement Pst = Con.prepareStatement("INSERT INTO organisateur (`Nom_os`, `Nom_org`, `Pre_org`, `Adr_org`, `Tel_org`, `Mail_org`) VALUES (?,?,?,?,?,?)");
                Pst.setString(1, nom_os.getText());
                Pst.setString(2, name.getText());
                Pst.setString(3, prenom.getText());
                Pst.setString(4, address.getText());
                Pst.setInt(5, Integer.parseInt(phone.getText()));
                Pst.setString(6,mail.getText());

                JOptionPane.showMessageDialog(null, "Organisateur ajoutée avec succès !");

                int row = Pst.executeUpdate();
                Con.close();
                
                ShowI();
                
                nom_os.setText("");
                name.setText("");
                prenom.setText("");
                address.setText("");
                phone.setText("");
                mail.setText("");
               
               

                
    // Code that may throw a SQLException or NumberFormatException
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Erreur de base de données");
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "Format de nombre incorrect");
}

 }
        
        
        
    }//GEN-LAST:event_addActionPerformed
        String Key = null;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int MyIndex = jTable1.getSelectedRow();
        Key = model.getValueAt(MyIndex, 0).toString();
        nom_os.setText(model.getValueAt(MyIndex, 1).toString());
        name.setText(model.getValueAt(MyIndex, 2).toString());
        prenom.setText(model.getValueAt(MyIndex, 3).toString());
        address.setText(model.getValueAt(MyIndex, 4).toString());
        phone.setText(model.getValueAt(MyIndex, 5).toString());
        mail.setText(model.getValueAt(MyIndex, 6).toString());
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed

           int index = jTable1.getSelectedRow();
   if (index == -1) {
        JOptionPane.showMessageDialog(this, "Veuillez sélectionner un organisateur à modifier.");
        }else {
            Connect_DB();
            try {
                PreparedStatement Pst = Con.prepareStatement("UPDATE `organisateur` SET Nom_os=? ,Nom_org=? ,Pre_org=?, Adr_org=?, Tel_org=?, Mail_org=? WHERE id_os=? ");
                Pst.setString(1,nom_os.getText());
                Pst.setString(2, name.getText());
                Pst.setString(3, prenom.getText());
                Pst.setString(4, address.getText());
                Pst.setInt(5, Integer.parseInt(phone.getText()));
                Pst.setString(6, mail.getText());
                Pst.setString(7, Key);
                
                JOptionPane.showMessageDialog(null, "Organisateur modifiée avec succès !");

                int row = Pst.executeUpdate();
                Con.close();
                ShowI();
                 
                nom_os.setText("");
                name.setText("");
                prenom.setText("");
                address.setText("");
                phone.setText("");
                mail.setText("");
                
               
                ///////////////////////////////////////////////// PROBLEM........
            } catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Erreur de base de données");
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(null, "Format de nombre incorrect");
}


        }
// TODO add your handling code here:
    }//GEN-LAST:event_EditActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Menu2 menuu = new Menu2();
menuu.setVisible(true);
this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        try {
            jTable1.print();
        } catch (PrinterException e) {
        }       }//GEN-LAST:event_PrintActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Organisateur2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Organisateur2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Organisateur2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Organisateur2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Organisateur2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Print;
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nom_os;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField prenom;
    // End of variables declaration//GEN-END:variables
}
